import { VisitPrescription } from '@/shared/graphql/generated/graphql';

export function generatePrescriptionPrintHTML(
  prescriptions: VisitPrescription[]
) {
  const p = prescriptions?.[0];

  return `
  <html>
  <head>
    <meta charset="UTF-8" />
    <title>Prescription Sheet</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">

    <style>
      body {
        font-family: 'Montserrat', Arial, sans-serif;
        padding: 40px;
        color: #0f172a;
      }

      .header {
        text-align: center;
        margin-bottom: 24px;
        border-bottom: 2px solid #e2e8f0;
        padding-bottom: 16px;
      }

      .org {
        font-size: 18px;
        font-weight: 700;
      }

      .meta {
        font-size: 12px;
        color: #64748b;
      }

      .section {
        margin-top: 20px;
        padding: 16px;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
      }

      .section-title {
        font-weight: 600;
        font-size: 13px;
        margin-bottom: 8px;
        color: #334155;
      }

      .grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 8px;
        font-size: 13px;
      }

      .card {
        border: 1px solid #e2e8f0;
        padding: 12px;
        border-radius: 8px;
        margin-top: 12px;
      }

      .drug {
        font-size: 15px;
        font-weight: 600;
      }

      .sub {
        font-size: 12px;
        color: #475569;
        margin-top: 4px;
      }

      .tag {
        display: inline-block;
        padding: 2px 8px;
        font-size: 11px;
        border-radius: 999px;
        background: #e0e7ff;
        color: #3730a3;
        margin-top: 6px;
      }

      .footer {
        margin-top: 40px;
        font-size: 11px;
        text-align: center;
        color: #94a3b8;
      }
    </style>
  </head>

  <body>
    <div class="header">
      <div class="org">
        ${p?.visit?.organization?.name || 'Hospital Management System'}
      </div>

      <div class="meta">
        ${p?.visit?.organization?.address?.addressLine1 || ''} 
        ${p?.visit?.organization?.address?.city || ''} 
        ${p?.visit?.organization?.address?.state || ''} 
        ${p?.visit?.organization?.address?.country || ''}
      </div>

      <div class="meta">
        ${p?.visit?.organization?.email || ''} | 
        ${p?.visit?.organization?.phoneNumber || ''}
      </div>
    </div>

    <div class="section">
      <div class="section-title">Patient Information</div>

      <div class="grid">
        <div><strong>Name:</strong> ${p?.visit?.patient?.fullName || '-'}</div>
        <div><strong>Gender:</strong> ${p?.visit?.patient?.gender || '-'}</div>
        <div><strong>DOB:</strong> ${p?.visit?.patient?.dateOfBirth || '-'}</div>
        <div><strong>Visit Type:</strong> ${p?.visit?.visitType || '-'}</div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Prescriptions</div>

      ${
        prescriptions.length === 0
          ? `<p>No prescriptions available</p>`
          : prescriptions
              .map(
                (p) => `
        <div class="card">
          <div class="drug">${p.drug}</div>

          <div class="sub">
            ${p.dose || '—'} • ${p.route || '—'} • ${p.frequency || '—'}
          </div>

          <div class="sub">
            ${p.startDate || '—'} → ${p.endDate || '—'}
          </div>

          ${
            p.isProvidedInHouse
              ? `<div class="tag">In-house medication</div>`
              : ''
          }

          ${p.notes ? `<div class="sub">Notes: ${p.notes}</div>` : ''}

          <div class="sub" style="margin-top:8px;">
            Prescribed by: ${p.prescribingDoctor?.fullName || '—'}
          </div>
        </div>
      `
              )
              .join('')
      }
    </div>

    <div class="section">
      <div class="section-title">Doctor</div>
      <div class="sub">
        ${prescriptions?.[0]?.prescribingDoctor?.fullName || '—'}
      </div>

      <div style="margin-top:30px;border-top:1px solid #cbd5e1;width:200px;"></div>
      <div class="sub">Signature</div>
    </div>

    <div class="footer">
      Generated by Hospital Management System
    </div>

  </body>
  </html>
  `;
}